#!/usr/bin/env bash

nvim_dir="$HOME/Personal/neovim"

if [ -d "$nvim_dir/.git" ]; then
  echo "Neovim source already exists. Updating..."
  cd "$nvim_dir"
	rm -rf build/
	make distclean
  git checkout stable
  git pull
else
  echo "Cloning Neovim stable..."
  git clone -b stable git@github.com:neovim/neovim.git "$nvim_dir"
  cd "$nvim_dir"
fi

brew list ninja cmake gettext lua@5.1 pkg-config curl git >/dev/null 2>&1 || brew install ninja cmake gettext lua5.1 pkg-config curl git

make CMAKE_BUILD_TYPE=RelWithDebInfo -j$(nproc)
sudo make install
