#!/usr/bin/env bash

if ! command -v rg &>/dev/null; then
  echo "Installing ripgrep..."
	if command -v brew &>/dev/null; then
    brew install ripgrep
  elif command -v pacman &>/dev/null; then
    sudo pacman -S --noconfirm ripgrep
  else
    echo "Unsupported system. Please install ripgrep manually."
    exit 1
  fi
else
  echo "ripgrep is already installed."
fi
