#!/usr/bin/env bash

if ! command -v tmux &>/dev/null; then
  echo "Installing tmux..."
	if command -v brew &>/dev/null; then
    brew install tmux
  elif command -v pacman &>/dev/null; then
    sudo pacman -S --noconfirm tmux
  else
    echo "Unsupported system. Please install tmux manually."
    exit 1
  fi
else
  echo "tmux is already installed."
fi
