gui:
  theme:
    activeBorderColor:
      - "#31748f"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    searchingActiveBorderColor:
      - "#ebbcba"
      - bold
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#403d52" # Rose Pine highlight_med (same as selection in Neovim popups)
    selectedRangeBgColor:
      - "#403d52"
git:
  log:
    showGraph: when-maximised
    showWholeGraph: true
os:
  editPreset: 'nvim'
  edit: 'if [ -n "$NVIM" ]; then nvim --server "$NVIM" --remote-send "<C-\><C-n><cmd>close<cr>" && nvim --server "$NVIM" --remote {{filename}}; else nvim {{filename}}; fi'
  editAtLine: 'if [ -n "$NVIM" ]; then nvim --server "$NVIM" --remote-send "<C-\><C-n><cmd>close<cr>" && nvim --server "$NVIM" --remote-send "<cmd>edit +{{line}} {{filename}}<cr>"; else nvim +{{line}} {{filename}}; fi'

